name: OverCube
version: '${version}'
main: fr.owtfox.overcube.OverCube
api-version: '1.19'
commands:
  report:
    description: Command to report a player
  grant:
    description: Command to increase a player's privileges (be overcube user)
  ungrant:
    description: Remove player privileges
  ready:
    description: Ready for overcube