name: OverCube
version: '${version}'
main: fr.owtfox.overcube.OverCube
api-version: '1.19'
commands:
  report:
    description: The command to report a player
  grant:
    description: Commande pour conferer la permission a un joueur de devenir overcube
  ungrant:
    description: Remove player privileges
  ready:
    description: Ready for overcube